management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: simple-client
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
      - org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration

springdoc:
  enable-native-support: true
  pathsToExclude:
    - /error.*
    - /actuator.*
#  swagger-ui:
#    enabled: false
#  api-docs:
#    enabled: false
